export const AUTHENTICATION_ACTION = {
    AUTHENTICATION_PROCESSING: "AUTHENTICATION_PROCESSING",
    AUTHENTICATION_SIGNIN_SUCCESS: "AUTHENTICATION_SIGNIN_SUCCESS",
    AUTHENTICATION_SIGNIN_FAILED: "AUTHENTICATION_SIGNIN_FAILED",
    AUTHENTICATION_SIGNIN_RESET: "AUTHENTICATION_SIGNIN_RESET",
    AUTHENTICATION_SIGNOUT: "AUTHENTICATION_SIGNOUT"
}

export const ACCOUNT_ACTION = {

}

export const DRINK_ACTION = {
    DRINK_PROCESSING: "DRINK_PROCESSING",
    DRINK_DATATABLE_SUCCESS: "DRINK_DATATABLE_SUCCESS",
    DRINK_SAVE_SUCCESS: "DRINK_SAVE_SUCCESS",
    DRINK_SAVE_FAILED: "DRINK_SAVE_FAILED"
}

export const LOCALSTORAGE = {
    ACCESS_TOKEN: "LOCALSTORAGE_ACCESS_TOKEN",
    USER: "LOCAL_STORAGE_USER"
}

export const FORM_OP = {
    EDIT: "edit",
    CREATE: "create"
}